
import random
import numpy as np
import csv
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score
import math

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

DATA_CSV = "healthcare.csv"  # generated by generate_dataset_regress.py

# --- 1) Load dataset
texts, intents, scores = [], [], []
with open(DATA_CSV, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        texts.append(row['text'])
        intents.append(row['intent'])
        scores.append(float(row['satisfaction_score']))

# Label mapping
intent_labels = sorted(list(set(intents)))
intent2idx = {l:i for i,l in enumerate(intent_labels)}
y_intent_idx = np.array([intent2idx[i] for i in intents])
y_score = np.array(scores).astype(np.float32)

# One-hot encode intents for multi-output regression targets
n_intents = len(intent_labels)
y_int_onehot = np.zeros((len(y_intent_idx), n_intents), dtype=np.float32)
y_int_onehot[np.arange(len(y_intent_idx)), y_intent_idx] = 1.0

# Combine targets: [one-hot intent (N dims) , satisfaction_score (1 dim)]
y_multi = np.hstack([y_int_onehot, y_score.reshape(-1,1)]).astype(np.float32)

# --- 2) Vectorize text
vectorizer = CountVectorizer(ngram_range=(1,2), min_df=1)
X = vectorizer.fit_transform(texts).toarray().astype(np.float32)

# --- 3) Train/test split (preserve mapping to original texts)
indices = np.arange(X.shape[0])
train_idx, test_idx = train_test_split(indices, test_size=0.20, random_state=SEED, stratify=y_intent_idx)
test_idx_list = list(test_idx)

X_train = X[train_idx]
X_test = X[test_idx]
y_multi_train = y_multi[train_idx]
y_multi_test = y_multi[test_idx]

# Also keep separate ground-truth arrays for evaluation convenience
y_int_test_idx = y_intent_idx[test_idx]
y_score_test = y_score[test_idx]

# --- 4) Single AI method: MLPRegressor (multi-output)
ai_method_short = "Neural Network"  # short method name to display
model = MLPRegressor(hidden_layer_sizes=(256,128), random_state=SEED, max_iter=400)

# Fit the single model to predict both one-hot intent and score
model.fit(X_train, y_multi_train)

# --- 5) Predict and extract outputs
y_pred_multi = model.predict(X_test)  # shape: (n_test, n_intents + 1)
pred_int_onehot = y_pred_multi[:, :n_intents]
pred_scores = y_pred_multi[:, n_intents]

# Convert predicted one-hot to class indices by argmax
pred_int_idx = np.argmax(pred_int_onehot, axis=1)

# --- 6) Overall Metrics (displayed in % where appropriate)
class_acc = accuracy_score(y_int_test_idx, pred_int_idx) * 100.0
r2 = r2_score(y_score_test, pred_scores)
r2_pct = r2 * 100.0
rmse = math.sqrt(mean_squared_error(y_score_test, pred_scores))
rmse_pct_of_scale = (rmse / 10.0) * 100.0  # score range 0-10

print("\n=== Evaluation metrics on test set ===")
print(f"Classification accuracy: {class_acc:.2f}%")
print(f"Regression R^2: {r2_pct:.2f}%")
print(f"Regression RMSE: {rmse:.3f} (which is {rmse_pct_of_scale:.2f}% of the 0-10 score range)")

# Combined metric: class correct and regression error within threshold
within_thresh = (np.abs(pred_scores - y_score_test) <= 1.5)
both_good = ((pred_int_idx == y_int_test_idx) & within_thresh).mean() * 100.0
print(f"Both-tasks acceptable (class correct & |error|<=1.5): {both_good:.2f}%")
print("======================================\n")

# --- 7) Two random test examples with clearly separated task displays
print("Two random test examples (each example shows Input, then separate Classification and Regression blocks):")
random.seed(SEED)
sample_orig_indices = random.sample(test_idx_list, 2)

for i, orig_idx in enumerate(sample_orig_indices, 1):
    text = texts[orig_idx]
    pos = test_idx_list.index(orig_idx)  # position inside test arrays
    pred_int_label = intent_labels[int(pred_int_idx[pos])]
    pred_score = round(float(pred_scores[pos]), 2)
    true_int_label = intent_labels[int(y_int_test_idx[pos])]
    true_score = round(float(y_score_test[pos]), 2)

    # Per-example metrics
    class_correct = 1 if pred_int_idx[pos] == y_int_test_idx[pos] else 0
    class_metric_pct = 100.0 * class_correct  # 100% if correct, 0% if incorrect
    abs_error = abs(pred_scores[pos] - y_score_test[pos])
    abs_error_rounded = round(float(abs_error), 3)
    error_pct_of_range = (abs_error / 10.0) * 100.0  # percent of 0-10 range
    error_pct_of_range_rounded = round(float(error_pct_of_range), 2)

    print(f"\nExample {i}:")
    print(f"AI Method: {ai_method_short}")  # AI method in bracket under Example label
    print(f"Input: {text}\n")

    # Classification block (separate)
    print("AI Task: Classification")
    print(f"Output (predicted label): {pred_int_label}")
    print(f"Ground-truth (label): {true_int_label}")
    print(f"Per-example metric: Correctness = {class_metric_pct:.0f}%")
    # Optionally show confidence-like signal from predicted one-hot magnitude
    pred_onehot_scores = pred_int_onehot[pos]
    top_score = float(pred_onehot_scores[pred_int_idx[pos]])
    top_score_pct = round(top_score * 100.0, 2)
    print(f"Model signal (predicted one-hot top value): {top_score:.2f} ({top_score_pct}%)\n")

    # Regression block (separate)
    print("AI Task: Regression")
    print(f"Output (predicted satisfaction score): {pred_score}")
    print(f"Ground-truth (score): {true_score}")
    print(f"Per-example metric: Absolute error = {abs_error_rounded} (which is {error_pct_of_range_rounded}% of 0-10 range)")
    # Show whether regression is within acceptable threshold
    within_flag = "YES" if abs_error <= 1.5 else "NO"
    print(f"Within acceptable error (<=1.5): {within_flag}\n")

    # Brief meaningful descriptions and combined value statement
    print("Brief meaningful input on each task:")
    print(f"- Intent (what the user wants): {pred_int_label}")
    print(f"- Satisfaction score (how satisfied/urgent): {pred_score}\n")

    value_desc = (
        "Value: Combining intent (classification) and a numeric satisfaction score (regression) from a single model "
        "lets organizations route and prioritize efficiently. Example: if intent='cancel_order' and the satisfaction "
        "score is low (small predicted value), escalate to a human agent; if intent='book_flight' and score is high, "
        "automate fulfillment and consider upsell. This single-model approach reduces latency and operational complexity "
        "while delivering richer signals for decision-making."
    )
    print(value_desc)

    # Separator for clarity
    print("-" * 80)

# Final note if below thresholds
if class_acc < 75.0 or r2 < 0.50:
    print("\nNote: classification accuracy below 75% or regression R^2 below 50%. Consider more data, tuning, or richer features.")
